### ISSUE TITLE
Prepare draft content for OAC 5.0 UX scoping (info architecture, annotated ArcLight layouts)

### ISSUE THREAD

**Issue by christinklez** [ucldc/cinco#7]

**Comment by aturner** [comment]
OAC 5.0 info. architecture ideas
https://www.canva.com/design/DAGScxb_teg/6DLRe-rLYwIDHPCDtZzTdw/edit?utm_content=DAGScxb_teg&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

OAC 5.0 site page ideas w/ annotations
https://www.canva.com/design/DAGSdyH9xYc/or2lhNCed5L4aA3Ekdw8Ig/edit?utm_content=DAGSdyH9xYc&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
